import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FilterProvider } from "./contexts/FilterContext";
import CartModal from "./components/modals/CartModal";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <FilterProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {/* <CartModal /> */}
          {children}
        </body>
      </html>
    </FilterProvider>
  );
}
